name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b98a4709e152caccf0695e098d1382dc0c429283f017711fae69c40b855a8c18"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
