name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72ce9e498a0e0682cea200ae20845b7be95203296d68b241fb27e83f31087064"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
