name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd656ac10c092c425fb3f96c399f9655ae2586964078c47e3cc5d9b1d15aa768"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
