name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41767951eebf0d3b1f1e03591ec584d77ab319503596b7da26b9a0c4bda22c4a"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
