name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f9abada8f128ef80f71af247e47db89fda1e174c5de9427cf9d60f92b2578b9"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
