name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f2d5cad16c37c3f239dc6f86b589e80ca5e68aea8d1d8c9c1571f8b733f753c"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
