hash-format = "sha256"

[[files]]
file = "config/defaultoptions/extra/betterf3.json"
hash = "92116c2244518636b04c850b9eda14b2f2f7613b01c6d4f26dae972e17ee57cf"

[[files]]
file = "config/defaultoptions/extra/fullbright.json5"
hash = "eb50ed0f49ba7150b00ef8a36b9b0de4a67b6d07005ca15f84c4329f62b3b6fc"

[[files]]
file = "config/defaultoptions/extra/inventoryprofilesnext/integrationHints/exampleIntegrationHints.json"
hash = "f0c885470e7ecdbed0a9fdf7cf584e84d8dfc200ca38a44e9bfaa773ee8800e2"

[[files]]
file = "config/defaultoptions/extra/inventoryprofilesnext/inventoryprofiles.json"
hash = "e96f5a09a30ad485789ccef302c970184de70c03e1b6ac75b5f7cfc2c7f43d87"

[[files]]
file = "config/defaultoptions/extra/sodium-fingerprint.json"
hash = "5cd905f82e3a30c36971df9efc3a6579d7a538ddb3dcbee22f6de0aa20a7efc4"

[[files]]
file = "config/defaultoptions/extra/sodium-mixins.properties"
hash = "5e979266f3c675f4c8c59ee8f60389ca778a71219d3d5a5d0006c9fd4e118bef"

[[files]]
file = "config/defaultoptions/extra/sodium-options.json"
hash = "13fd4385072407c196a7b9d8be554f18afceab44249eb28ad41d49da26fe97bb"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "51f01fb16d4047db393ce57b16330ef68ce70c741a6d13325fe6be82eca17e33"

[[files]]
file = "config/defaultoptions/options.txt"
hash = "bbee2050e5bf04bd54d2ab067b74366cac75e4414d7b4f2c5e17146a8bff3b9c"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "b930d7ca8bc035dae2798ae1628dd240d53520c2ad6b38323eb1fbda47c165b5"
metafile = true

[[files]]
file = "mods/allow-portal-guis.pw.toml"
hash = "2b7615fcb74ea6e56330fce8c262983ee2c48dac501ca58e3c1b1e5d726351cc"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "d7666f6a123377a79457a8a41429c40812eb9393518872bf42876a25f01a262d"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "377ec48bec937867b812345798dc6890b48ccbb9169c3d2cd7e16158eb08bb70"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "6b79b32a6ead0fef2198277b04ef36f7c2532e0f241655cd689073c4a2da3684"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "04ea90d7f044fda95ef97c2e034f8e731be4d07487ee8f6d8263f8370a2f8d54"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "15362f0288935041938b2a4428592a34997a2a897482dec73f5b4a9bd1a6b940"
metafile = true

[[files]]
file = "mods/better-beds.pw.toml"
hash = "c394b32bf31dd06a7afec731b4034dae070042abe7ad78f764d7e6dab51ddd5c"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
hash = "effae993d050253e64f8244d96c8e62643afdebec6be4ae67b1088898d0cf7b1"
metafile = true

[[files]]
file = "mods/better-compatibility-checker.pw.toml"
hash = "3c0d9b6764a38cf6d65e7bf96f23a543e13a221f2ef807f0d9cf3a074902c00b"
metafile = true

[[files]]
file = "mods/better-ladders.pw.toml"
hash = "853894690d8f12bb58ba6297a04f708a6354b3a71002f0c2f005cb7347d8a564"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "c8dfe64fa3714b7b5c68766d9ed3d76a4b996774059357661810ebc0ec3f05f4"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "d10943c2422ee3d9fb2fe93d4885f314df562a1d0a7719be4f66b8e3af1a3b1a"
metafile = true

[[files]]
file = "mods/betteraddserver.pw.toml"
hash = "b9cd83082902cbb4bae41486b2ebf4f3ce0af6f3cd6a0a93dbdfb61e8e6e443e"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "e86141672e63e5021fa6bd97b407b71409796dfdaff9190599919bf8fab0661a"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "6ec5134ef5b2d7c39f3cf90440160db115568fdc3cc9a9142b2f0104a09f49ea"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "2bac6347331408aa47194a62322a324ee3869938b24240ac187dde9dafbd1bf6"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "e35119f9a16cfcb7f88a54fccd9a44db2ba3ec7387f2789894416eb563fd7382"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "c4b947529291fa0d5dbeefe2c9d292750318744b9c4609af50c7a687d2389e19"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "482d76ed37105900217410824ffb46c5b09c7d1a5c98d1197dedb8e028305e70"
metafile = true

[[files]]
file = "mods/click-through-updated.pw.toml"
hash = "9a5cf40f5baf43fa234b7fa1cec135acabba8fc9d67925d5110557534864e1a0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "12f8afafa9be01ba7fd1d18319c26b6a572626a2af9a377f849fbd7149eed59d"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "8924fed64fc638922e3ddebf457247fc8000d80699925a234e6577f595077b95"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "9a3a1a5da0d8b062eb5fc992562db7eca595ab1f7f57c8677ac09635832e2dec"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "27fa211d3e56415d0fb0847a2d3f6f0be1bfcb918e565e574ccd548f3f755dd2"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "6be8fb59d83334f347c981444e7fbb81686bf3530f49436d6bc3a9a18e2dd772"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "d6f07ddf39ab1db474f4d6d89c4d3eb9b8ec903051aead4fb7b5ad0e996b4c55"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "23ff99c403531967dea9de0d8022c2a74abc865661615470b837a7344aef1304"
metafile = true

[[files]]
file = "mods/crying-ghasts.pw.toml"
hash = "bff75229d8326e385c4bb0d590411e2dc6bac71a6ed9e479b21641c6b35b97d2"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "798368990e285406bf81744842f2a156b27349365f84088e280001bd9df978d1"
metafile = true

[[files]]
file = "mods/easyauth.pw.toml"
hash = "68452d7f7f35fd0857c2732c191347a37d4749180d299b2eba48350503a9b54e"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "2b36f02811ed714fc6a3aacb5266eba3449d1b659bda8c8177b58a9cec7d8f70"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "bea9d9c7604dc01b5fb3d2ba111b1e7cd47c8fba50452e847668a4fe3e22b8c8"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "837533e26d797461fe5e2abbc3c35c4a162f17f0764aef23e1690ac2130c2266"
metafile = true

[[files]]
file = "mods/entity-view-distance.pw.toml"
hash = "83b00fe3916e64428ea25aff782bc460c96b6a3ddf1ce3a694a7d42ed04f7e9a"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "0b36fb5bf8ab36e4b655ef850a0ad80cbd8ddb00f611e7e5e6b4898a0cd96c6d"
metafile = true

[[files]]
file = "mods/esf-entity-sound-features.pw.toml"
hash = "f86d3a626ece53158ae9ebb0691eebeae2345e16fe9c78eb777a7b9511cfb071"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "415701f7ddad9230491adf5d85dd37a2b94e82e91ba0178fce3de5ccd6ef2299"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d5877de3e42cf3cbb287b779e37d8a8053c8aa1365aec2a66c95e3bf411d79e1"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "051fa06d39d7be9097cf2c86da297fda796532938ed4e3bdbe01ae01d0efb8b2"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "29924dca0fc8d1e64f4d9cd1c377607d34a831c37822075b3f5bf3834471baa3"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "aaad4f1b2f56017174e616998d03895c79b457868dfcc7d308bb1137ca24f1c0"
metafile = true

[[files]]
file = "mods/feytweaks.pw.toml"
hash = "fdf3368940666ce88dd176501311e2a9e476d001c55104d3e8d2c8e69dc9b557"
metafile = true

[[files]]
file = "mods/followers-teleport-too.pw.toml"
hash = "c9497a18ed577280959044e1ea054904b877671ea3b2e65b11e035c9cf161c17"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "69360e5ed734eee0e5623e0ed320a89501088b0fa83a1d7f1879edd6703fa17c"
metafile = true

[[files]]
file = "mods/fullbright.pw.toml"
hash = "803f112161f2a1e7cb9abd7bda38e830360f0a01fe2395be261bee350c3627a6"
metafile = true

[[files]]
file = "mods/gputape.pw.toml"
hash = "b4e6cdc2bc413496bf895b960b117ed59e998f4952a64f20de2672cde1132694"
metafile = true

[[files]]
file = "mods/grind-enchantments.pw.toml"
hash = "a2db2a713129e60b9abc823b5df0c492cd145c4a30bc34210867485464f779d7"
metafile = true

[[files]]
file = "mods/head-in-the-clouds.pw.toml"
hash = "992fe7c44b672d10db2cc32d87d82ec3e73cdaede288b3c268b99412aa30d033"
metafile = true

[[files]]
file = "mods/healing-campfire.pw.toml"
hash = "e85f6947159f6a6bd56209f48116d0f156267bbd514744e16f9ca74f670d9c4a"
metafile = true

[[files]]
file = "mods/hold-that-chunk.pw.toml"
hash = "88d504ca7157466de1a296c456a95e20412bf14bec48e606499fe3319a9ddbab"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "f8372cba601b3c38f58fbcaa3f8f093471ec4d8440bca0363d41da422c6b96d1"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "a9c4f8a7acd7cf535101744919136cc2f6a024c925227726242fbe981d4750fd"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "78d73be72a5bbbc5d05ee639e4ba26b2bcef8dc9fb30a9626a8c4f9d2df1bec8"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "e8591cd7c781f48b66fcd2c49c80ee162b6d7023e060f9ca5ffaee7e05cc6565"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "757249dc1c0a84a89c5739511bed1654fa158dfee514c17ce748a82113a776ab"
metafile = true

[[files]]
file = "mods/leashable-players.pw.toml"
hash = "ee9bfaa51dd4378ccda9e100dd3bf8a17c30ecb6d85aa126290bc60fe7c305ce"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "f31d71b17407e1d3f8111f1d616161ecf1680f02f0d10722746c5514694d45a6"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "23de9b25d5ba1ff89859ca0177b06ab68bd26abcfd690add05b49b6f06f985e6"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "05abca9865677dfdf99cd0fc9c8cba993cf67bfa2bd244a0fea28e6daed69a76"
metafile = true

[[files]]
file = "mods/logical-zoom.pw.toml"
hash = "4afad61e5ae61bc3e71a752c990569b5db15139fb8e53d2f6b6a69e9cf73dc6b"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "79f0958db94d007778f03da083f9d75077978e3cc04b23f1081ecb2d6a4906b4"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "6a06688ca0c0fc3038b8b2ed438ffd4e6cc5e0edeb26d0b40fbca1e6b44b8ee8"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "e74b111babc68645bb3246fd17f835e168f982d65cfda7b306565fc29ce121c9"
metafile = true

[[files]]
file = "mods/mineral-chance.pw.toml"
hash = "abdf5ede82902d9197009404c085ebb27cc2b4ced676f0e598c66df354794950"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "ad48dafd3729ceb57c9facae1be79e5f4b3d711e385296bab44ec5c3b9aced39"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "6c10583f8b19da6e4ee53458062ecf29adf5cc11bd0ffdad8675001a8bdb3d5d"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "eb9611ea2482c61bfb5616eed361f52c55d5d49a1235bb0167ff872c0d4d076c"
metafile = true

[[files]]
file = "mods/monsters-in-the-closet.pw.toml"
hash = "24d46db1dcb51219d7cde079628f94f3d1ced872712b5ad8394a54088ac992f8"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "cfc991da3e1adfc2866d3a537466624b3a9725bf37aa35bdb8a2a1f7a992f561"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "818bccff58d1a7e0e6b89512201a3861186c7cc45b66f5a2e7facbdc4503fa71"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "a8678bed0852d8e6ced390140ee33c27a3708d3df79e1a265cfc6d9de6720d9a"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "d27ba77245964a94bb474ee91e0f7e4d908c9a890109ded6ee48716f5a6b36dc"
metafile = true

[[files]]
file = "mods/no-hostiles-around-campfire.pw.toml"
hash = "7fa3f2f798b04f20573d7b517aa582a9bd211049ebd1335863338cf4319b7fcc"
metafile = true

[[files]]
file = "mods/nonetherite.pw.toml"
hash = "b916af8da349cad2705e45ebccfd3e7c1960eba2876c0ac84de221c76a9f2d70"
metafile = true

[[files]]
file = "mods/offlineplayers.pw.toml"
hash = "5dd9396231f24e79fde72a9bc87fd157f0b5d530e9556ff948a47f76f1f5edb7"
metafile = true

[[files]]
file = "mods/optipainting.pw.toml"
hash = "dc894dc23a92b1b03ac04466e3f4a3f4d33b52a707daed0f7d9d50e05c8aecdb"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "ccf5fe8b6c310a3f26ff40495dbd1884c1f2b097ec54063493b7248a53282f1b"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "0b13a6bc0eb7d984dfb7150ad1e82ebf39d651ed01522e5f34c970f3efe8729f"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "f7f1fc9893f87b24d1ea2989646cf17ec30370a9beda51dcc8d8128010f5ab71"
metafile = true

[[files]]
file = "mods/player-pronouns.pw.toml"
hash = "4a050bf74bf3df4fb235e64b0eedb2299cce451a629e328a9e3cfabd2b3f6f21"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "f865d16ce7d7e9df3afceca357d14d8c6a5065857487361d055ffac2c06f394a"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "5f4f2fb3291ca69266fbd240b275d6f52f2e0d71a863be8aa5fc6bb926c9be41"
metafile = true

[[files]]
file = "mods/scaffolding-drops-nearby.pw.toml"
hash = "5f0ab12bbff6195dd3c445ab1aadd2bccd71123eba5dc9512660524d9cc5c393"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "9e8a2866ed79d6a3e578e03159eabd164980342e2a134e717f9402c3299a8330"
metafile = true

[[files]]
file = "mods/sdlink.pw.toml"
hash = "9b27ba08d8ca896c01a0e0a65573af52ad713801905998733ce7531e529e3bf6"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "51ab75f65e28a29c2a1b9f325d248278da337e97c968941d33211e028614343c"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "bb3ad8120da2925c843fa86068421649c7c1bcf71a667fc345bc572d257a3184"
metafile = true

[[files]]
file = "mods/simple-discord-rpc.pw.toml"
hash = "545b2600a4734f4858661cceb3e696e86c366d81793d4733a49e2ff079a15963"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "088b6cddbd6ed317d9e527d949b3144e7bc1c35355c3f9ec4caa7cb96815965f"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "9551a3adda2e5c7d0070a8cae2dfae82cc5aa5f650fe317fe97c4148981692f1"
metafile = true

[[files]]
file = "mods/snow-under-trees-remastered.pw.toml"
hash = "cc28759943fcbb2281e39c3034e34da4fdc1ee6cfcf7b78d6ad212424d53d2c3"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "12c8a078a90db9552b664ef413267ef3cbf6237cde20157a2474a507a7bf3030"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "01cda3aee3fee4c2b1adf3b90cf3e41c4bcdd07daeb3c52dee89e278c3c014b3"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "363daf799768b7508e9090ad21c521a766f4bd26b00f42f8a3bd9b39f8a451f0"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
hash = "8065d5d410ac1732586237b3678aa55c8094d49773b758dfb2c38223600e7120"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "aeaddc3079ff5c180495b1721ede27d87bd1ef717d8623f4fac4784cbed3419e"
metafile = true

[[files]]
file = "mods/toggle-item-frames.pw.toml"
hash = "3f9f109ccf5964c4dfb6e2ddd527d06360642552637e55a6bf52f41cf81e845d"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "fe592547ec2aedf1de7add34f747f7845e103de228e2426328e9e60fe93298cc"
metafile = true

[[files]]
file = "mods/unloaded-activity.pw.toml"
hash = "fc1c283d82aecd05d52f2f11928af45ff6877d73b851185ce75b206d71d89dc6"
metafile = true

[[files]]
file = "mods/villager-names-serilum.pw.toml"
hash = "738220ab4bc5377128f107b836feaa4fadb276e1f33f702f510dbd727ede9ac2"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
hash = "7dde8bc5c61c3baab2c8139c5c26d17cdb2f2e6236c58e5b98c65740b488d494"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "8bbf5cc48030422cc1ce318d54dcc4671a1530556c544dce255ef9d232815b49"
metafile = true

[[files]]
file = "mods/where-is-it.pw.toml"
hash = "c833519664d90e076b0fdb8d82ac9cd94190bbed7bb4be0b68b2df19870ba971"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "e32b05fdd1c9accfa40cf04cb4cfcec01f511e5f3ca27d3083a3755436a88c1b"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "d8b1a8b5ec1ebb5d1c1505d1aecac1cee43866f7013d2c9f9cf7231e6839124f"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "bb9e068343ecde349c91f5607d7901dad9c0f3f9979cab3bb8ab844d10d1d5cd"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "cfe99033f8c6220d174e7a075530a9d7102acad07af54181da49c008550410f0"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "256b67c869770482657d4dd31124bf705c780c5c798206af522bcd5392c7ded9"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "4f2a665064101a215bc230f9b4a52e62b39f776a452cca33637b142c84731217"
metafile = true
