hash-format = "sha256"

[[files]]
file = "config/defaultoptions/extra/betterf3.json"
hash = "93982f0f58dd38da1891f5b2b4e70a4080bd58337be871abd00bbab9e89f9b60"

[[files]]
file = "config/defaultoptions/extra/fullbright.json5"
hash = "61a225e91c1a48c979b26241fc75d4c5a4ae8e4733c730dfe6502fa45c404109"

[[files]]
file = "config/defaultoptions/extra/inventoryprofilesnext/integrationHints/exampleIntegrationHints.json"
hash = "ca413dea02cce69c69dccdc525fb0ec013236876eff2d142772c68db3d772d3a"

[[files]]
file = "config/defaultoptions/extra/inventoryprofilesnext/inventoryprofiles.json"
hash = "8e6eef77570026aa6453aaf3107d8e3074a540908c4314b3c0959e4e7c6b3f17"

[[files]]
file = "config/defaultoptions/extra/sodium-fingerprint.json"
hash = "5cd905f82e3a30c36971df9efc3a6579d7a538ddb3dcbee22f6de0aa20a7efc4"

[[files]]
file = "config/defaultoptions/extra/sodium-mixins.properties"
hash = "8939df3a10627cf3b9a3cc0e2824337923e9a26d11e60f5a1f7c0cfbd171a574"

[[files]]
file = "config/defaultoptions/extra/sodium-options.json"
hash = "ad965d43182e6ad90c5e9ef129555b0f03b1ad767d4b72ad25864508d1a1d199"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "1df1ab7de7dc07b35028513d19ae5283f0e66290e687e2ed11034249e211a87b"

[[files]]
file = "config/defaultoptions/options.txt"
hash = "073524495b171b1e35856f7344c8bdd6bb56a77a2c95dd6167290da3eba62300"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "1afa3d4cc64e64899fd0c113936d8bef92e5a99aab3d42b14269503582fd38a8"
metafile = true

[[files]]
file = "mods/allow-portal-guis.pw.toml"
hash = "e69e4f7a6814fbe208dab0cb1a2f0e6ccf20f11793479ccae0d53fa0ae853b51"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "20f677dc377f5069c8da4636cb7bcf068fbca27a60fda63ac9e2fe273fa9f765"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "af482cdaf7c5d9d5481e7cd789d98ebc17f47e4565a28af6c6365aef896d1404"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "417b7af3c7cb5f2681960349d3fa118733cbce5d260fadddd792abb24e52fbdc"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "77cba89986eae4a5a2d693a2e169cd91338127f625663bc26741094a75616bbb"
metafile = true

[[files]]
file = "mods/better-beds.pw.toml"
hash = "15c2128399c6f09974ca5af95281e1139744a1dfac9f96d0d9ee1002579676cc"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
hash = "6ebf6f01a8550fddd86b8eab37957fa5e6c1d48701271010c4d38b2292f7f7f2"
metafile = true

[[files]]
file = "mods/better-compatibility-checker.pw.toml"
hash = "09cf79c795abb54ac59f81a8abc23968e149102317523a7e8cdc7b72423fbcfc"
metafile = true

[[files]]
file = "mods/better-ladders.pw.toml"
hash = "fd6d88f171bab25da3ad2565881f7e021633c165f98fc0885563000c1eea5e10"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "a934007a85cf1a0d1a1c28cd8d4f1eff250e6536ea7243813cf91d82b0708b2b"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "941bf61ed32600eefffb76356799bbb7cd1a3d1775a6f478cb69657fc8bcccc5"
metafile = true

[[files]]
file = "mods/betteraddserver.pw.toml"
hash = "df45b3315d2976099eb9a5075f862135782018d566519bd4e15a71ab7eccffee"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "d69de5e020139a28ca7b7256ad6f1d598ba09a1b6b051e326fc28261cf4f12b7"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "7e149f7e7c028f692a331b828b9ad8b84ca2029c8ffe765e19f7a647653e77a9"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "4f1b12a40251eb9cee6edbafb43387bf82bed56f272b6d012f5fad61538b0a10"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "95c94d93fcdd5f07f3a71790d0c50f5f75ef0563521d3c9d1405f957e3f0e7f5"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "53ee326e24bd8d6c2f1f6b4aa1f5256c0821fe0b9793d800e7e45d0f4c8a019c"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "da4f0d277bd0dd7137f79b3faa5f19e7d16f5352a6ed2d2d6a4789621c3492ea"
metafile = true

[[files]]
file = "mods/click-through-updated.pw.toml"
hash = "f38b4ef67bfd722a353c978d41f381655b50cd7c36ee133caeea99026b6c99a0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "cfc2c53b0d3cee953b423fe9abf210d87281d5bf774dab20cf03abe6224a9883"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "f0ec653fdb2ea3c2546cbe327d1d184256548be6fe9e459885eb0f9459153dae"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "901e954cfcd2fcb7928b95959c7688fa0b210c6ad67d0f3f2f7e54ee939c839c"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e5cbc5221d474cb7e95447c5bccd5be8a1e7df24b4416dc3b694b7c7141f68c1"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "0f06ba5b409ad41ccb7c2356b1407fe751bf3794386d8ddca924475f74c50822"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "896b70a8d8df3786cc31fc602d9d4a90fc70d55fb803f3b95add08119e4780d5"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "aa6914e50a5bc531fc8c4f6d3ad8244e06335ee5068ec6ad879af1e80d5294ba"
metafile = true

[[files]]
file = "mods/death-finder.pw.toml"
hash = "3b9da6e082bdda5a04995d31490133f996d1da725e8d3c32fed057f12c53e59b"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "a7a9eee6eafe7a6e6a17bc9c00738be97e476639561e08c42c8a6d64854c17f2"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "c60b48beafb80503417feb7400e091e1651ca966851ffb763780f4278987d2ae"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "8a114ea0fda082e82adb39d5a684c0f24eda5c91dd6f09ba0ca6fd83106676eb"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "f3375f22b9ef0f00d52f5150a0b3edc6085fd4930bb0d4573dee813bcb2b398b"
metafile = true

[[files]]
file = "mods/entity-view-distance.pw.toml"
hash = "2c707336883229e55c6a4278e9a37ccba55d6d85f34fa7c90221807b6dce9644"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "444ec76f51b9713378aa4c900ca583a7df0888f89e76b76ae8cf5293d9cb51ab"
metafile = true

[[files]]
file = "mods/esf-entity-sound-features.pw.toml"
hash = "a4f30f44f2d509074c1094fccedb106374337bb4d7bc0481e630a83c99f1681c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "40ec6cacc1f65f3aac6f72a14f95e59a76d907cd8804c0441a06d9e06fa4a73c"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "4827c2c799732112b14c0edf55062c1f33bef97d7f7d866491bb1d7d4b97e1c8"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "9b561d57bf92aa8005e567e4bb95a2b65c8ed9c3ab30de09ea6c7e66f2e4d2da"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "c0f791cad09e48ac8875162a148314a6e1e5b7190819e820197e5bbd3c7f439e"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "078c828454d8a361baae372b5ee3dc33e5f3573fa19bdac8589b38da9dbc5c03"
metafile = true

[[files]]
file = "mods/feytweaks.pw.toml"
hash = "1e4034d327b8fde6937692ea0bfd91c571b27669624c1b429fe349415233b72f"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "2645fbb800b5c53e3e8937489dcf036b9c40cfdc3d8674d6231a5f0fd0a7aeff"
metafile = true

[[files]]
file = "mods/fullbright.pw.toml"
hash = "8e8ebae780f0e0605aedf9fa2d12d0e8aaa874cde2fea0821f566cccfe02cf0f"
metafile = true

[[files]]
file = "mods/gputape.pw.toml"
hash = "6e4d625a8bd6dba83cbe603b7fc95aea226b054c825012b3b17ec3cdf23dd387"
metafile = true

[[files]]
file = "mods/head-in-the-clouds.pw.toml"
hash = "678c6215a26d45947a2046d0f0267fc5a21dac84ce535fd974718c6b728c0f66"
metafile = true

[[files]]
file = "mods/hold-that-chunk.pw.toml"
hash = "88d504ca7157466de1a296c456a95e20412bf14bec48e606499fe3319a9ddbab"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "fea164dda1332d54afd1365311ba0a548fb11a475a6490026a1f00a7aa70400d"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e16a6442391c1989dccdcbe100e13063a043caef70b13ab4e37a11a7861cb497"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "715fd75311a3b112aa6261123603b0e45f0c73cf8fb99c85a4dedd4288366f0f"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "d3e29c543dd1ff3acfe8c0a044e391237069d4023637be567516ebd6b832b02b"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "4ee72fa3b6d91ccec6ec3420396db368dc5097350ee2bb909af3a65f0446c9d5"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "87d16fb355306f86a437eaeb3b3674ec7b56f72ac90ee71300772f4920fe1b10"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "a39cd82e397036a3c1d886a0cce33539fa13163358559f229adc6cc7cdb2192b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c24fcd33ecd783569879dbe9ecb8cdd1dcc7e00c1f40cda0271100255e155162"
metafile = true

[[files]]
file = "mods/logical-zoom.pw.toml"
hash = "3a71b4b8d7067aaa21e17ae5e62c1e16942798e4eb20f068926a6e8a5321ca82"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "79f0958db94d007778f03da083f9d75077978e3cc04b23f1081ecb2d6a4906b4"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "f3b85761b078d82f78acc2eb7dc490b3b70d25c304eb9af9dcd553ba796f7559"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "03075a32803d3cd0e574a043156599231d7d01661179b1c4c1a527ea7a1c539d"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "e2cc568688c5bcd0e41235681bc34c5c9849f214f65b43324bc25022d9ad8c80"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "8db4414ae685883aaa38fba9d9412962338585c231b20b1770b20a119a0d5ba6"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "2b8ce9ab97a35059a79d59d540687385d25956c519ce1728fbcfb13fae93a328"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "90f207724a47d6b32f45c6a53da2539f544df944709418761ec8ede01a401a47"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6ff1d7cc8800c891723375aea3426b9b2f50400798374e8f97f96e804cc5c518"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "100a5dfaccb55b107edc57e11fafc1222dc443ce9b669f0d79a39b488e3e45ae"
metafile = true

[[files]]
file = "mods/nonetherite.pw.toml"
hash = "b916af8da349cad2705e45ebccfd3e7c1960eba2876c0ac84de221c76a9f2d70"
metafile = true

[[files]]
file = "mods/optipainting.pw.toml"
hash = "dc894dc23a92b1b03ac04466e3f4a3f4d33b52a707daed0f7d9d50e05c8aecdb"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "705b12953afb39daf0def61796eb3e59e562c3781d0b6283db0e5ffd85464036"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "17dcc67a3af6e13b6b487c55b8bcefe90f8fa15232bb8cecb90c3d0fa16aa299"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "d0311de4c47e48ba0c1769253c7bd8fd541ed81c60823c539116a963e58c9128"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "c6b51dc747962dfd44c614072b4c5effd1c9262c112aab5d48c7d4371309bcea"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "138929792a63cb1ab3794f91703149555a9ca94bb64011b8f0db62f8b55d9bea"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "c803d271faae47b193e3ba9ca611894252bf55d4c6aab303f56bcf6b183056c7"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "9071356a9c92d249941a89c5ef62a18041846ef3bb8ecb0396defaa6f811ab51"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "27f31e3c878723e5502bc5860c84e5a0d92016e77a7bd0b654251627f8387beb"
metafile = true

[[files]]
file = "mods/simple-discord-rpc.pw.toml"
hash = "4bbb611ecb06e6623618cf3f1db99c8fce842af602d3470cafe16607b26f947c"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "3ea99db242c72753682ecb03faf2d367e1cbf8de0b5cbb4691180d107b06a8fa"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "32183306d7fd027a408716bc1d40b66f50fdeb5ecb5ad5ee3309f7c89bd00da4"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "47870c885ade491cf58a094e23b9e1d53f12e7ae738d933c26f60290c6259edd"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "a07734892496719d75a5ad73a8d53950469ffa2348df1aac07a75a6c304271a6"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "fe592547ec2aedf1de7add34f747f7845e103de228e2426328e9e60fe93298cc"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "4bff412d3a71ce97141788f987fb30f50a97b86896207de205d571bc78027e86"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "5e11f4117ac8601737ecf9a7e244f7b3ef34af23e474cf54fa3fffe4a747062a"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "c06ffc9de8c8b6c1e9099c05fcfa94d9ae9bff768ff138798ab3a2da545995d5"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6a22d14251ccfb61007da299c1040bcb3904bd0cc43e5d1ba96536b94ed43036"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "256b67c869770482657d4dd31124bf705c780c5c798206af522bcd5392c7ded9"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "f18e6196d79be05795c41658af6ea9ad77457bb65058bdd65a0ef5d3c6f30ca0"
metafile = true
