hash-format = "sha256"

[[files]]
file = "config/betterf3.json"
hash = "88c1d481b1048c62d228e356ecd683b1128dfba8693921080a6a8660e1def2a4"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "2d664c7a158125bbf21318ae0822e1b3a8c51545a3b4647fed00c92a7cccb771"

[[files]]
file = "config/iris.properties"
hash = "f59cc592e42d9fb44b09135c6ea71a1e171c500319724a67fbe59b4fa3503231"

[[files]]
file = "config/lithium.properties"
hash = "76765e8e5ff8e927d80beb0739aababcf36e7babfd94262f2afece256cc5cd2e"

[[files]]
file = "config/waveycapes.json"
hash = "5da4eb2ba4994c75d2d379dd8d6040da12d6bd9b5f10b8a90836acfb1a8a7907"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "1be52fb2cc3326852135b2edc897507da41480abaa7c8d08dfbc87c77a8354c5"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "fe48ef33fd4a8d8580fd938b7a6a7c1175aad76e0df0ddf4c12e7acb2f0ea65a"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "6511f2eae25781b5859b6f7b450773ae84643b6aefcbef768264284fb477ce0f"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "e9999d5ccd9cba3a02989e8887ee877e9dcf2daf6fb6d5aa8f1c960e42de6669"
metafile = true

[[files]]
file = "mods/better-beds.pw.toml"
hash = "0bf7fa5d6e5b126e110699e85c64b4d86a1d4171d17adfc994936e6f62b81083"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "ec31177d5cf656efdff737432455211defb8ee188749e3f53f117f75f83d1b6a"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "8b13db034aecef8d45addf4f12aa024d35b905ae144df48542683e1b162ba4f9"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "fbba50d7962a2f9b75b4765b71f19e30c2864b3c863bb1b93d881d2d5c358e07"
metafile = true

[[files]]
file = "mods/centered-crosshair.pw.toml"
hash = "34cb6130b98838c53e562ade7d27509bad75e2e123b3d0f674855553802fa764"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "8c8a9578de59d6ceb9a1d6ca825b1ce8a3a679a35bd91513a8ad7bb54c925f9c"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "7a4414a95295f22f036699300878058ddf043659fc95ac1bf1d7f725acb0bc46"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "dbede39f3ccff414382384857789cb049c3525fcc8cc7209295743ffd92e4730"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "f250d6778f5b8d03ca32913bea5ea677508e9bb6d8201cdebe005bbe9c3100ee"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "7dd609edc5df00b01caebb7c29f6437c8fefde1af1a9a06fa6c4e4607a9ed231"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "b39cd19687d468d8389881a144f40b676bd1af134aaa05bcf6e784e6736b14fa"
metafile = true

[[files]]
file = "mods/creeper-healing.pw.toml"
hash = "0c010b32989ab8320ce35fd0efbf41112543684b5d03dedc82cdc8d8b64742ad"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "f9f4439a50f6de55c91eab4c2dcbe1a6c9c325a7b87d1b579c79a6098f5dedc1"
metafile = true

[[files]]
file = "mods/deathlog.pw.toml"
hash = "4bf0a9827aec78e4c94fe3889bfe97449ca2107751bfdf6b1203749c30c76c3f"
metafile = true

[[files]]
file = "mods/disable-elytra.pw.toml"
hash = "b34d9d19f5a0810aee76034e4bc52462b629e08d22bf024bb544d4329577ff88"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "593bd80e28f34a29b94107c6b88cb3fa7362f65c99a87971fcb8e50a7b98aa2a"
metafile = true

[[files]]
file = "mods/dripsounds-fabric.pw.toml"
hash = "6992619452254eac894dbaaaff722c4dfa3d3576405f1b3c4d9782fe98aaf7e1"
metafile = true

[[files]]
file = "mods/easyauth.pw.toml"
hash = "74cb4754dd26809b128f6c13947c449f7ec345fd678a2d699357db50a0cec1a1"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "1c0633f52455c5c6db31b4d926acbbaa0890d771177b55e33eb245a7bc63b635"
metafile = true

[[files]]
file = "mods/entity-view-distance.pw.toml"
hash = "668e6be6338e6b3e61fb80e0b8d404c2d18ad5e8328fe2e78cf9334b4f49e5ab"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "880d7fcdbf0bc9e1e7e5ff3b120e9667245708a5d144b5afbad32bf39c7fc1f9"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "350e3aa46726c4ce33c9c383c673ab131c76c9015b5aa8c5532521beed1dfca4"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "fe7dbe82cf758cc6a73e96f57229e6be3696588388da757fbd936ac8c08c224f"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "14e87ff6253d2bd02697e46b4a9b5060465d72b71663def5236f829e30bac6d6"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "b91224d8b6110cbeca20c7905f2ae6032e8ccd992733829fbc6a79d2da957839"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "948e8a5d65ede4a8612a2f476d7b3b0f2fe00436ab3b8dd73829d4bdcf0cdf22"
metafile = true

[[files]]
file = "mods/feytweaks.pw.toml"
hash = "b2d8b9ab4612676712d43d98428eb50729a26ddcd09ec230605e50cbcc7ec048"
metafile = true

[[files]]
file = "mods/healing-campfire.pw.toml"
hash = "36916bb5d47e7052cedfbb19268044214c180a624c641b3f5c37756a9fc14e72"
metafile = true

[[files]]
file = "mods/hold-that-chunk.pw.toml"
hash = "88d504ca7157466de1a296c456a95e20412bf14bec48e606499fe3319a9ddbab"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "f91f449f949d8618e231fa4a64b8715c49d13030779273cfa0b7a5f889b4c0ed"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "72e4c374b0f8085b2b96e84f8f43e6953d82b0342445c69e224ac2ef71ca890e"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "b8452fc314e3a49f6bb226004c5afe81a2d383480ba15b85581390f2bf2aa877"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "fe6abe1ea33393fe1441801f79eda74ea892e5f4b677a56eccafafcbf4d253ca"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/leaves-us-in-peace.pw.toml"
hash = "b5533b3bafe4c5ea6280f4794aaf40d04763a554ccaec4248a693da0d6882c79"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "46775cb51714cb624ab336889c25c29945998c67b8f32f8fb11e9fb7ecf50c67"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3dedde5213176d72e1c353877fa44315945e8f3da2ba05f5679d81e9f558bb1d"
metafile = true

[[files]]
file = "mods/logical-zoom.pw.toml"
hash = "5db239b544cde5a3b02418c239b72e16be00b2522abe94c6caabc37864ebab9a"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "ac2ca5caef9ddb4fd53c035bfaf07026f12bcdb162d19c2fa473bdec8fbec630"
metafile = true

[[files]]
file = "mods/minimotd.pw.toml"
hash = "28c115a5d999a96d39a31b333ad4e3798ef363281d07bf8c6e967ff27d7e6400"
metafile = true

[[files]]
file = "mods/mixin-conflict-helper.pw.toml"
hash = "c7388b6ebb78040be98251fb064a009f3d7574133e15d2844e3fadf2929b2980"
metafile = true

[[files]]
file = "mods/mobhealthindicators.pw.toml"
hash = "bb616141b0cad99126df9aaaadbca565735acfc3827e42e433ef8e6842fc2b0e"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "6ff047f3b0e73e22bf5ad0d6751f82cd6f6a4e164a911a37839eba667fa85502"
metafile = true

[[files]]
file = "mods/modern-beta.pw.toml"
hash = "9557009bff6fd7d1be4db8f40b8e561c3336d2d7da9a06e448f8e8555ae65c57"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d6aecbaf1fbfa8c4bd57184d515892c40f6fd00ed9c265468059d72c028a48aa"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "d2cf752938bcc2e83b8389fc1c6fc0557eb6a8b721fd33733b89f1a09fb535e5"
metafile = true

[[files]]
file = "mods/netherite-beacons.pw.toml"
hash = "e9a03373a7862768c29a4eab13fbdb15ace3181aa965e8c073476132b45bd387"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "a6a57004f5990ae59be0b89eb2edc5f50e2233d0410bd5f8060d58401592e0ef"
metafile = true

[[files]]
file = "mods/no-hostiles-around-campfire.pw.toml"
hash = "ee69f8a0f92e3751afe5e3ac09622c3d90478be2191bba801334e35e7b59ea82"
metafile = true

[[files]]
file = "mods/nonetherite.pw.toml"
hash = "b916af8da349cad2705e45ebccfd3e7c1960eba2876c0ac84de221c76a9f2d70"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "7b79a6c0397c3e1f5811508cf89cd99dea35d6a5363c247731b63a974eeaf7ee"
metafile = true

[[files]]
file = "mods/nvidium.pw.toml"
hash = "07dd8775324c01058896b4572e23a1ca1c355186cc501c61fc68e1151c5e177c"
metafile = true

[[files]]
file = "mods/optipainting.pw.toml"
hash = "dc894dc23a92b1b03ac04466e3f4a3f4d33b52a707daed0f7d9d50e05c8aecdb"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "7c647f3090c57732c32306de0a080ea190ec6562af5dbc2be3e7a9d4cadc8b7c"
metafile = true

[[files]]
file = "mods/perfect-accuracy.pw.toml"
hash = "b12911fc5e1c093bc33cad60ec0c741a6066783cecdb5750d2c8124463aabef3"
metafile = true

[[files]]
file = "mods/playerhealthindicators.pw.toml"
hash = "a8528a56fa7cd6780fb6f4725f6886bb922d6c7a4d8d6230cc6c6e3a68745d99"
metafile = true

[[files]]
file = "mods/raknetify.pw.toml"
hash = "776a8c141073e136f9b13daef58089b6e3b19bc86940b52d65bc57a637bacdd5"
metafile = true

[[files]]
file = "mods/seedguard.pw.toml"
hash = "9cb9a3c5609f02977b77bb39339f0e9ddb69fabb6c6b11ef726b44a2ea57bde0"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "35898748f3395a94e14dc72b52d9d4b9e15f4aad97628f46c4f5160dd1ed8aab"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "8ef792d3eeb1e5d220a01ba035c887afc4cfd06f8b5daffe2770bdb6a6bef512"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "3a125e342d3a410f67643d264c097501cb10723fe5244321ef2ee055956b0678"
metafile = true

[[files]]
file = "mods/sleep-warp.pw.toml"
hash = "25c6c26c56658a11b6cdd930ba2403817c52718824033077615890a1d00ece32"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "5e73967368d47038c38dc52fa298b45603fbe6baf2608f171638ff767178ad9a"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "69150600dff0e73fd78a041c53dfc1d264a6eda7b0d6ea36cf53db6f8478de6f"
metafile = true

[[files]]
file = "mods/takeaseat.pw.toml"
hash = "e7d83c44d8b4fa9eace4955a20175e1900376b4d6cbe2416e7b052f8e68b20d0"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "fe592547ec2aedf1de7add34f747f7845e103de228e2426328e9e60fe93298cc"
metafile = true

[[files]]
file = "mods/view-distance-fix.pw.toml"
hash = "3bb9908f2f52099808d7b0adbc559c2061ad090784b8af66c0a48d52d45890d6"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
hash = "d4654e71ed969ebc1beab111a46c2061468d7539fb050112779cbcd798a7e009"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "50c7a9d1825bdf0579a4a1e76587db455f0f0dc224543900b118d7c5349c4c03"
metafile = true

[[files]]
file = "options.txt"
hash = "e9694ae44e4c3fd2b6e51eb950e12c70e15ee757d1ae104eaa166e64ff4b7c11"

[[files]]
file = "resourcepacks/faithless-mod-patch.pw.toml"
hash = "bd5a99861a26bc361365eed1905a37db38012a2cd608b22d22787bb80dbe6e20"
metafile = true

[[files]]
file = "resourcepacks/faithless-music-disk-mono.pw.toml"
hash = "a52023e87504c3e4acd530f616bab1fedc8ded6bc9882299ad4177d7274fd992"
metafile = true

[[files]]
file = "resourcepacks/faithless-ogtextures.pw.toml"
hash = "53da2ac4f70a52dfb6acc242510b9390961da98fc175fa1d76075b043c5c7708"
metafile = true

[[files]]
file = "resourcepacks/faithless-vanillactm.pw.toml"
hash = "22ab55807851172a2c52f32926888135a62e74a2b47a8f94efd3d2429e7b24ef"
metafile = true

[[files]]
file = "resourcepacks/faithless.pw.toml"
hash = "16833981fc2919119693ee040e8c113e04220de8f70c8d47b001f9a439c48767"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "0a4676b25054d0bd8cc97adc49b2fca2e4af4f2c92fc3dca484c7fea169aebff"
metafile = true

[[files]]
file = "servers.dat"
hash = "e2c664edf5c310013afe00887a07c1d457acc7ce580df037686f5d8840c7500f"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "170a8817f93b22938e19e75afc44cc9d42f0ced575ce3c3dc9b3a2fee102f657"
metafile = true
