name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "2.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0818c4d925a434c3c16728b0118503e025b7210022fe54df8d74bfa21de54ab"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
